version: '3.8'

services:
  core:
    build:
      dockerfile: docker/Dockerfile
      context: .
    container_name: recrawler
    environment:
      - HOST=db
      - PORT=3306
      - MYSQL_DATABASE=recrawler
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=passwd
    entrypoint: ["tail", "-f", "/dev/null"]
    volumes:
      - .:/usr/src/app
    depends_on: ["db"]

  db:
    container_name: db_scrapper
    image: mysql:8.0.35
    platform: linux/amd64
    environment:
      - MYSQL_DATABASE=recrawler
      - MYSQL_ROOT_PASSWORD=passwd
    ports:
      - 3306:3306
    restart: always
    volumes:
      - ./docker/mysql/scripts:/docker-entrypoint-initdb.d:rw