package webcrawlers.fotocasa.specification;

public enum Home {
  FLATS,
  ALL_THE_HOUSES,
  INTERMEDIATE_FLOOR,
  APARTMENT,
  PENTHOUSE,
  DUPLEX_APARTMENT,
  LOFT,
  GROUND_FLOOR,
  STUDIO,
  CHALET,
  SEMI_DETACHED,
  RURAL_PROPERTY
}
