name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17
      - name: Maven test
        run: mvn -B clean test
      - name: Maven Verify
        run: mvn -B clean verify -q
