name: Feature Branch

on:
  push:
    branches-ignore:
      - 'master'

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21
          cache: maven
      - name: Maven test
        run: mvn -B clean test
      - name: Maven Verify
        run: mvn -B clean verify -q
